# Generated by Django 3.0.5 on 2020-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_applicationsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubject',
            name='name_az',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='applicationsubject',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='applicationsubject',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
