# Generated by Django 3.0.5 on 2020-04-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200421_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Müraciət', 'verbose_name_plural': 'Elektron müraciətlər'},
        ),
        migrations.AlterModelOptions(
            name='applicationsubject',
            options={'verbose_name': 'Mövzu', 'verbose_name_plural': 'Müraciət mövzuları'},
        ),
        migrations.AlterField(
            model_name='application',
            name='content',
            field=models.TextField(verbose_name='Müraciətin mətni'),
        ),
        migrations.AlterField(
            model_name='application',
            name='department',
            field=models.CharField(max_length=250, verbose_name='Struktur vahidi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='application',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tarix'),
        ),
        migrations.AlterField(
            model_name='application',
            name='request_type',
            field=models.CharField(max_length=100, verbose_name='Müraciət növü'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Müraciət mövzusu'),
        ),
        migrations.AlterField(
            model_name='applicationsubject',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Mövzu'),
        ),
        migrations.AlterField(
            model_name='applicationsubject',
            name='name_az',
            field=models.CharField(max_length=150, null=True, verbose_name='Mövzu'),
        ),
        migrations.AlterField(
            model_name='applicationsubject',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Mövzu'),
        ),
        migrations.AlterField(
            model_name='applicationsubject',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Mövzu'),
        ),
    ]
