# Generated by Django 3.0.5 on 2020-04-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='link_name_az',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='link_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='link_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
