# Generated by Django 3.0.5 on 2020-04-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200419_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_1', models.CharField(max_length=20)),
                ('phone_number_2', models.CharField(max_length=20)),
                ('tel_1', models.CharField(max_length=20)),
                ('tel_2', models.CharField(max_length=20)),
                ('fax_number', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('address_az', models.CharField(max_length=250, null=True)),
                ('address_ru', models.CharField(max_length=250, null=True)),
                ('address_en', models.CharField(max_length=250, null=True)),
                ('address_map_link', models.CharField(max_length=250)),
            ],
        ),
    ]
