# Generated by Django 3.0.5 on 2020-04-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
