# Generated by Django 3.0.5 on 2020-04-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200420_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakt'},
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Keçid üçün linklər'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=250, verbose_name='ünvan'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_az',
            field=models.CharField(max_length=250, null=True, verbose_name='ünvan'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=250, null=True, verbose_name='ünvan'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_map_link',
            field=models.CharField(max_length=250, verbose_name='naviqasiya linki'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='ünvan'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=150, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax_number',
            field=models.CharField(max_length=20, verbose_name='faks'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number_1',
            field=models.CharField(max_length=20, verbose_name='əlaqə nömrəsi 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number_2',
            field=models.CharField(max_length=20, verbose_name='əlaqə nömrəsi 2'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link_name',
            field=models.CharField(max_length=150, verbose_name='Linkin adı'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link_name_az',
            field=models.CharField(max_length=150, null=True, verbose_name='Linkin adı'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Linkin adı'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Linkin adı'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link_url',
            field=models.CharField(max_length=250, verbose_name='Keçid üçün url'),
        ),
    ]
