# Generated by Django 3.0.5 on 2020-04-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
    ]
