# Generated by Django 3.0.5 on 2020-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='tetle_en',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
