# Generated by Django 3.0.5 on 2020-04-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_tetle_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='title_az',
        ),
    ]
