# Generated by Django 3.0.5 on 2020-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200417_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title_az',
            new_name='title',
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
