# Generated by Django 3.0.5 on 2020-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200417_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
        migrations.RemoveField(
            model_name='about',
            name='language',
        ),
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='content_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
