# Generated by Django 3.0.5 on 2020-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20200418_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_az',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
