# Generated by Django 3.0.5 on 2020-04-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20200418_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
