# Generated by Django 3.0.5 on 2020-04-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20200419_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_ru',
        ),
    ]
